//CONTADOR
export const INCREMENTAR= 'INCREMENTAR';
export const DECREMENTAR= 'DECREMENTAR';
export const INCREMENTAR_5= 'INCREMENTAR_5';
export const DECREMENTAR_5= 'DECREMENTAR_5';
export const RESET= 'RESET';


//SHOPPING CART

export const TYPES_CART = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_COUNT: "ADD_COUNT",
  REST_COUNT: "REST_COUNT",
  REMOVE_ONE_FROM_CART: "REMOVE_ONE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
};

//CRUD

